# Generated by Django 4.2 on 2026-04-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numControl', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('primerAp', models.CharField(max_length=50)),
                ('segundoAp', models.CharField(max_length=50)),
                ('fechaNac', models.DateField()),
                ('semestre', models.IntegerField()),
                ('carrera', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
    ]
