# Generated by Django 6.0.4 on 2026-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolares', '0002_alter_alumno_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('usuario', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
